#!/bin/bash
# Record Circuit Weaver MVP demo video (20-50 seconds)
# Usage: ./record_demo.sh

OUTPUT_FILE="${1:-circuit_weaver_demo.mp4}"
DURATION="${2:-40}"  # seconds

echo "[*] Circuit Weaver Demo Recording Script"
echo "[*] Output: $OUTPUT_FILE"
echo "[*] Duration: $DURATION seconds"
echo ""
echo "[!] Requirements:"
echo "    - ffmpeg installed (ffmpeg.org)"
echo "    - Chrome/Firefox for browser recording (or manual screen capture)"
echo ""
echo "[*] Recording methods:"
echo ""
echo "Method 1: Browser Recording (Recommended)"
echo "  1. Open http://localhost:8090 in Chrome/Firefox"
echo "  2. Open DevTools (F12)"
echo "  3. Use Chrome's built-in recording:"
echo "     - Sources tab → Recorder"
echo "     - Click through workflow: Define → Validate → Generate → Review → Export"
echo "     - Export as MP4"
echo ""
echo "Method 2: Screen Capture with ffmpeg"
echo "  $ ffmpeg -f gdigrab -i desktop -t 40 -c:v libx264 circuit_weaver_demo.mp4"
echo ""
echo "Method 3: OBS Studio (Advanced)"
echo "  - Download OBS from obsproject.com"
echo "  - Open http://localhost:8090"
echo "  - Record window (40 seconds)"
echo "  - Export as MP4"
echo ""
echo "[*] Demo script (terminal-based):"
echo "  Would show:"
echo "    1. YAML spec file (battery_iot_sensor.yaml)"
echo "    2. Validate command output (green checkmarks, warnings)"
echo "    3. Generate command (schematic + report generated)"
echo "    4. Generated report displayed"
echo "    5. Export JLCPCB command (BOM/CPL ready)"
echo ""
echo "[+] Demo is ready at: http://localhost:8090"
echo "[+] Port: 8090"
echo "[+] Server running in background"
echo ""
