"""Parametric enclosure generator for PCB designs.

Generates OpenSCAD files for 3D-printed enclosures that match PCB dimensions.
Supports customizable wall thickness, port cutouts, mounting holes, and vents.

Usage:
    from circuit_weaver.enclosure_designer import generate_enclosure_scad

    scad_code = generate_enclosure_scad(
        board_width_mm=100,
        board_height_mm=80,
        board_thickness_mm=1.6,
        component_height_mm=12,
        wall_thickness_mm=2.5,
        clearance_mm=2,
        ports=[
            {"type": "usb_c", "side": "front", "x_offset": 10, "y_offset": 5},
            {"type": "round", "diameter": 3, "side": "back", "x_offset": 50, "y_offset": 40},
        ],
        mounting_holes=[
            {"x": 5, "y": 5},
            {"x": 95, "y": 5},
            {"x": 5, "y": 75},
            {"x": 95, "y": 75},
        ],
    )
"""

from __future__ import annotations

import logging
import subprocess
from dataclasses import dataclass
from pathlib import Path
from typing import Any

log = logging.getLogger(__name__)


@dataclass
class PortSpec:
    """Port cutout specification."""

    type: str  # "usb_c", "usb_micro", "barrel", "round", "rectangular"
    side: str  # "front", "back", "left", "right", "top", "bottom"
    x_offset: float  # mm from corner
    y_offset: float  # mm from corner
    width: float = 10  # for rectangular ports
    height: float = 6  # for rectangular ports
    diameter: float = 3  # for round ports


def generate_enclosure_scad(
    board_width_mm: float,
    board_height_mm: float,
    board_thickness_mm: float = 1.6,
    component_height_mm: float = 12,
    wall_thickness_mm: float = 2.5,
    clearance_mm: float = 2,
    ports: list[dict[str, Any]] | None = None,
    mounting_holes: list[dict[str, float]] | None = None,
    top_height_mm: float | None = None,
    vents: bool = False,
) -> str:
    """Generate parametric OpenSCAD code for a PCB enclosure.

    Args:
        board_width_mm: PCB width in mm.
        board_height_mm: PCB height in mm.
        board_thickness_mm: PCB thickness (default 1.6mm).
        component_height_mm: Max component height above PCB (default 12mm).
        wall_thickness_mm: Enclosure wall thickness (default 2.5mm).
        clearance_mm: Extra clearance inside enclosure (default 2mm).
        ports: List of port cutout specs (USB-C, barrel, round, rectangular).
        mounting_holes: List of M3 mounting hole positions [{x, y}, ...].
        top_height_mm: Override calculated lid height.
        vents: Include vent holes in top cover.

    Returns:
        OpenSCAD code as a string.
    """
    ports = ports or []
    mounting_holes = mounting_holes or []

    # Dimensions in mm
    inner_w = board_width_mm + 2 * clearance_mm
    inner_d = board_height_mm + 2 * clearance_mm
    inner_h = board_thickness_mm + component_height_mm + clearance_mm
    outer_w = inner_w + 2 * wall_thickness_mm
    outer_d = inner_d + 2 * wall_thickness_mm
    outer_h = inner_h + wall_thickness_mm

    if top_height_mm is None:
        top_height_mm = wall_thickness_mm + 3  # Lid height

    # Port cutout functions
    port_functions = _generate_port_functions(board_width_mm, board_height_mm, wall_thickness_mm)

    # Mounting hole functions
    mount_functions = _generate_mount_functions(mounting_holes)

    # Vent holes (optional)
    vent_code = _generate_vent_code() if vents else ""

    scad_code = f"""// Parametric PCB Enclosure
// Generated by Circuit Weaver
// Board: {board_width_mm}×{board_height_mm}mm, Component height: {component_height_mm}mm

// ========== Parameters ==========
board_w = {board_width_mm};
board_d = {board_height_mm};
board_h = {board_thickness_mm};
comp_h = {component_height_mm};
wall = {wall_thickness_mm};
clr = {clearance_mm};

inner_w = board_w + 2*clr;
inner_d = board_d + 2*clr;
inner_h = board_h + comp_h + clr;

outer_w = inner_w + 2*wall;
outer_d = inner_d + 2*wall;
outer_h = inner_h + wall;

top_h = {top_height_mm};

$fn = $preview ? 24 : 60;

// ========== Modules ==========

{port_functions}
{mount_functions}

module main_body() {{
    difference() {{
        // Outer shell
        cube([outer_w, outer_d, outer_h], center=false);

        // Inner cavity
        translate([wall, wall, wall])
            cube([inner_w, inner_d, inner_h + 0.5], center=false);

        // Port cutouts
{_generate_port_cutouts(ports)}

        // Mounting holes
{_generate_mount_cutouts(mounting_holes, wall_thickness_mm)}
    }}
}}

module lid() {{
    difference() {{
        // Lid outer dimensions
        translate([0, 0, outer_h - top_h])
            cube([outer_w, outer_d, top_h], center=false);

        // Lip recess for snap fit
        translate([wall + 0.5, wall + 0.5, outer_h - top_h + 0.5])
            cube([inner_w - 1, inner_d - 1, top_h], center=false);

        {vent_code if vent_code else "// No vents"}
    }}
}}

// ========== Assembly ==========

color([0.9, 0.9, 1], 0.8)
    main_body();

color([0.7, 0.7, 1], 0.6)
    lid();

// ========== Measurements ==========
// Outer: {outer_w}×{outer_d}×{outer_h}mm
// Inner: {inner_w}×{inner_d}×{inner_h}mm
// Wall thickness: {wall_thickness_mm}mm
// Mounting holes: {len(mounting_holes)} M3 holes
// Ports: {len(ports)} cutouts
"""

    return scad_code


def _generate_port_functions(board_w: float, board_d: float, wall: float) -> str:
    """Generate helper functions for port cutouts."""
    return """
module port_usb_c() {
    // Standard USB-C cutout: 8.94×3.26mm
    cube([10, 4, 5], center=true);
}

module port_usb_micro() {
    // Micro USB: 7.5×2.5mm
    cube([9, 3, 4], center=true);
}

module port_barrel() {
    // 5.5mm barrel jack
    cylinder(d=6, h=5, center=true);
}

module port_round(d) {
    // Generic round port
    cylinder(d=d+0.5, h=5, center=true);
}

module port_rect(w, h) {
    // Generic rectangular port
    cube([w+0.5, h+0.5, 5], center=true);
}
"""


def _generate_port_cutouts(ports: list[dict[str, Any]]) -> str:
    """Generate port cutout code."""
    if not ports:
        return "        // No ports"

    code_lines = []
    for i, port in enumerate(ports):
        port_type = port.get("type", "round")
        side = port.get("side", "front")
        x_offset = port.get("x_offset", 0)
        y_offset = port.get("y_offset", 0)

        # Translate based on side
        if side == "front":
            x = x_offset + 0  # Centered on front edge
            y = y_offset
            z = -1
        elif side == "back":
            x = x_offset
            y = y_offset
            z = -1
        elif side == "left":
            x = -1
            y = y_offset
            z = y_offset
        elif side == "right":
            x = -1
            y = y_offset
            z = y_offset
        else:
            continue

        if port_type == "usb_c":
            code_lines.append(f"        translate([{x}, {y}, {z}]) port_usb_c();")
        elif port_type == "usb_micro":
            code_lines.append(f"        translate([{x}, {y}, {z}]) port_usb_micro();")
        elif port_type == "barrel":
            code_lines.append(f"        translate([{x}, {y}, {z}]) port_barrel();")
        elif port_type == "round":
            diameter = port.get("diameter", 3)
            code_lines.append(f"        translate([{x}, {y}, {z}]) port_round({diameter});")
        elif port_type == "rectangular":
            width = port.get("width", 10)
            height = port.get("height", 6)
            code_lines.append(f"        translate([{x}, {y}, {z}]) port_rect({width}, {height});")

    return "\n".join(code_lines) if code_lines else "        // No ports"


def _generate_mount_functions(mounting_holes: list[dict[str, float]]) -> str:
    """Generate mounting hole specifications."""
    return """
module mount_hole() {
    // M3 screw hole with countersink
    cylinder(d=3.2, h=20, center=true);
}
"""


def _generate_mount_cutouts(mounting_holes: list[dict[str, float]], wall: float) -> str:
    """Generate mounting hole cutout code."""
    if not mounting_holes:
        return "        // No mounting holes"

    code_lines = []
    for i, hole in enumerate(mounting_holes):
        x = hole.get("x", 0) + wall
        y = hole.get("y", 0) + wall
        z = 10  # Center height
        code_lines.append(f"        translate([{x}, {y}, {z}]) mount_hole();")

    return "\n".join(code_lines) if code_lines else "        // No mounting holes"


def _generate_vent_code() -> str:
    """Generate vent hole pattern."""
    return """// Vent holes (5mm grid)
        for (x = [10:10:outer_w-10])
            for (y = [10:10:outer_d-10])
                translate([x, y, outer_h + 1])
                    cylinder(d=2, h=3);"""


def render_enclosure_stl(scad_path: Path, output_path: Path | None = None, timeout: int = 60) -> Path | None:
    """Render OpenSCAD file to STL using CLI.

    Args:
        scad_path: Path to .scad file.
        output_path: Output STL path (default: same name, .stl extension).
        timeout: CLI timeout in seconds.

    Returns:
        Path to rendered STL, or None if OpenSCAD CLI unavailable.
    """
    if output_path is None:
        output_path = scad_path.with_suffix(".stl")

    try:
        result = subprocess.run(
            ["openscad", "-o", str(output_path), str(scad_path)],
            capture_output=True,
            text=True,
            timeout=timeout,
        )
        if result.returncode == 0:
            log.info("Rendered %s → %s", scad_path.name, output_path.name)
            return output_path
        else:
            log.warning("OpenSCAD render failed: %s", result.stderr[:200])
            return None
    except FileNotFoundError:
        log.debug("OpenSCAD CLI not found on PATH")
        return None
    except subprocess.TimeoutExpired:
        log.warning("OpenSCAD render timeout (%ds)", timeout)
        return None
